# Generated by Django 6.0.2 on 2026-02-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_answer', 'Nie odebrano'), ('talked', 'Odebrano - rozmowa'), ('call_later', 'Zadzwonić później'), ('not_interested', 'Nie zainteresowany'), ('interested', 'Zainteresowany')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('next_contact_date', models.DateField(blank=True, null=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
            ],
        ),
    ]
