# Generated by Django 6.0.2 on 2026-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Nowy'), ('no_answer', 'Nie odebrano'), ('talked', 'Odebrano - rozmowa'), ('call_later', 'Zadzwonić później'), ('not_interested', 'Nie zainteresowany'), ('interested', 'Zainteresowany'), ('rejected', 'Odrzucony')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('file', 'Plik'), ('referral', 'Polecenie')], default='google_maps', max_length=50),
        ),
    ]
