# Generated by Django 6.0.2 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_importfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Nowy'), ('no_answer', 'Nie odebrano'), ('talked', 'Odebrano - rozmowa'), ('call_later', 'Zadzwonić później'), ('not_interested', 'Nie zainteresowany'), ('interested', 'Zainteresowany'), ('client', 'Klient'), ('rejected', 'Odrzucony')], default='new', max_length=50),
        ),
    ]
