# Generated by Django 6.0.2 on 2026-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cold_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
