# Generated by Django 6.0.2 on 2026-02-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_cold_email_sent_lead_email_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='is_reminder_active',
            field=models.BooleanField(default=False),
        ),
    ]
