# Generated by Django 6.0.2 on 2026-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_calllog_is_reminder_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('uber_eats', 'Uber Eats')], default='google_maps', max_length=50),
        ),
    ]
