# Generated by Django 6.0.2 on 2026-02-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_leadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='analysis_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
