# Generated by Django 6.0.2 on 2026-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_analysis_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='type',
            field=models.CharField(choices=[('call', 'Telefon'), ('email', 'Email')], default='call', max_length=50),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('no_answer', 'Nie odebrano'), ('talked', 'Odebrano - rozmowa'), ('call_later', 'Zadzwonić później'), ('not_interested', 'Nie zainteresowany'), ('interested', 'Zainteresowany'), ('email_sent', 'Wysłano email')], max_length=50),
        ),
    ]
