# Generated by Django 6.0.2 on 2026-02-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_leadcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('dataforseo_login', models.CharField(blank=True, max_length=255)),
                ('dataforseo_password', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ustawienia aplikacji',
            },
        ),
        migrations.CreateModel(
            name='GoogleBusinessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('has_description', models.BooleanField(default=False)),
                ('has_website', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_hours', models.BooleanField(default=False)),
                ('photos_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_analyses', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
