# Generated by Django 6.0.2 on 2026-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_appsettings_googlebusinessanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='business_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='description_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='description_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_menu_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_social_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='hours_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='keywords_used',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='last_post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='menu_items_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='owner_responses_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='posts_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='primary_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='secondary_categories_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='website_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
