# Generated by Django 6.0.2 on 2026-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_googlebusinessanalysis_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='status',
            field=models.CharField(choices=[('fetched', 'Pobrano dane'), ('analyzed', 'Analiza gotowa'), ('error', 'Blad')], default='fetched', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
