# Generated by Django 6.0.2 on 2026-02-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_googlebusinessanalysis_status_lead_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlebusinessanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pobieranie...'), ('fetched', 'Pobrano dane'), ('analyzed', 'Analiza gotowa'), ('error', 'Blad')], default='fetched', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='leads.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
