# Generated by Django 6.0.2 on 2026-02-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_googlebusinessanalysis_status_leadkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRankCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_checks', to='leads.leadkeyword')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
