# Generated by Django 6.0.2 on 2026-02-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_keywordrankcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSuggestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Generowanie...'), ('ready', 'Gotowe'), ('error', 'Blad')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_batches', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('ai_rank', models.IntegerField(default=0)),
                ('ai_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='leads.keywordsuggestionbatch')),
            ],
            options={
                'ordering': ['ai_rank'],
            },
        ),
    ]
