# Generated by Django 6.0.2 on 2026-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_keywordsuggestionbatch_keywordsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
