# Generated by Django 6.0.2 on 2026-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='next_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
