# Generated by Django 6.0.2 on 2026-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_calllog_next_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='posts_count_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='posts_status',
            field=models.CharField(choices=[('pending', 'Pobieranie...'), ('fetched', 'Pobrano'), ('error', 'Blad'), ('unavailable', 'Brak CID')], default='unavailable', max_length=20),
        ),
    ]
