# Generated by Django 6.0.2 on 2026-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_googlebusinessanalysis_posts_count_plus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlebusinessanalysis',
            name='ai_summary',
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='custom_summary_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='description_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_menu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='has_social_media',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='name_recommendation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googlebusinessanalysis',
            name='website_recommendations',
            field=models.TextField(blank=True),
        ),
    ]
