# Generated by Django 6.0.2 on 2026-03-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_usercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Nowy'), ('no_answer', 'Nie odebrano'), ('talked', 'Odebrano - rozmowa'), ('call_later', 'Zadzwonić później'), ('not_interested', 'Nie zainteresowany'), ('interested', 'Zainteresowany'), ('client', 'Klient'), ('rejected', 'Odrzucony'), ('close', 'Zamknięte'), ('complete_profile', 'Kompletny profil')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadPipelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_entries', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entry', to='leads.lead')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leads.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leads.pipeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadPipelineStepHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_step_moves', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_history', to='leads.leadpipelineentry')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='leads.pipelinestep')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
        migrations.AddField(
            model_name='leadpipelineentry',
            name='current_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_entries', to='leads.pipelinestep'),
        ),
    ]
