# Generated by Django 6.0.2 on 2026-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_pipeline_alter_lead_status_leadpipelineentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='show_on_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
